name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: core/build/reports/jacoco/test/jacocoTestReport.xml
        
  upload-coverage:
    name: Upload Coverage
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.repository == "farmdawgnation/repo-policy" }} # only run on main repo
    
    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: code-coverage-report
    - name: Upload code coverage
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: jacocoTestReport.xml
